go.mod: upgrade to go-fuse v2.7.2
Done using: go get -u github.com/hanwen/go-fuse/v2

As expected, this breaks TestSeekDir:

gocryptfs/tests/defaults$ go test -run TestSeekDir
test_helpers: warning: testParentDir "/tmp/gocryptfs-test-parent-1026" does not reside on ext4, we will miss failures caused by ino reuse
--- FAIL: TestSeekDir (0.00s)
    main_test.go:536: 1st getdents returned 288 bytes
    main_test.go:542: 2nd getdents returned 0 bytes
    main_test.go:551: operation not supported
FAIL
exit status 1
FAIL	github.com/rfjakob/gocryptfs/v2/tests/defaults	0.030s